import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH } from "@bridge/shared";
import { db } from "../db/client.js";
import { users, sessions, accounts, verifications } from "../db/schema/index.js";
import { env } from "../config/env.js";
import { emailProvider } from "../email/email.factory.js";
import { logger } from "../observability/logger.js";

const SESSION_MAX_AGE_SECONDS = 60 * 60 * 24 * 30; // 30 days
const SESSION_UPDATE_AGE_SECONDS = 60 * 60 * 24; // rotate session token daily on active use
const SESSION_COOKIE_CACHE_MAX_AGE_SECONDS = 60 * 5; // 5 minutes

/**
 * ADR-003: Better Auth was chosen deliberately over Firebase/Clerk to keep
 * identity data inside our own Postgres graph rather than externalizing it.
 * That decision came with an explicit obligation: because we don't inherit
 * a managed provider's hardening for free, this configuration has to spell
 * it out. Do not simplify this file to "just the defaults" — every
 * non-default option below is here because the v1.1 architecture review
 * flagged auth as needing an explicit hardening pass, not a bare wire-up.
 *
 * RISK FLAGGED FOR PHASE REVIEW (see Phase 1 report "Security"): the
 * `schema` mapping and `user.additionalFields` shapes below are authored
 * from best-recollection of Better Auth's documented Drizzle-adapter API,
 * without live-docs access to confirm the exact current shape for the
 * pinned version (^1.0.0). Two things specifically need verification
 * against a real `pnpm install` before this is trusted:
 *   1. That `additionalFields` field keys/types below match what the
 *      installed version expects (type literals, `input`/`required` keys).
 *   2. That Better Auth writing `status` as a plain string is compatible
 *      with `status` being a Postgres enum column (identity.schema.ts) —
 *      if the adapter ever attempts to write a value outside
 *      `userStatusEnum`'s allowed set, Postgres will reject it. If that
 *      surfaces, the fix is changing `status` to `text` with an
 *      application-level check rather than a DB enum — not applied here,
 *      since that's a schema change outside this fix's scope.
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    // Maps Better Auth's internal model names to our actual Drizzle
    // tables — required because our tables live under core/db/schema
    // rather than being generated by Better Auth's own CLI.
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,
  trustedOrigins: [env.WEB_ORIGIN],

  // Bridge-specific columns on the `user` table (phone, status,
  // lastLoginAt — see identity.schema.ts) registered so Better Auth reads
  // and writes them through the same adapter, rather than a second,
  // disconnected write path directly against Drizzle.
  user: {
    additionalFields: {
      phone: { type: "string", required: false, input: true },
      status: { type: "string", required: false, defaultValue: "active", input: false },
      lastLoginAt: { type: "date", required: false, input: false },
    },
  },

  emailAndPassword: {
    enabled: true,
    minPasswordLength: PASSWORD_MIN_LENGTH,
    maxPasswordLength: PASSWORD_MAX_LENGTH,
    // Mandatory verification — an unverified account cannot be treated as
    // "the same person" anywhere else in Bridge's identity graph, which
    // undermines the whole product thesis in VISION.md.
    requireEmailVerification: true,
    sendResetPassword: async ({ user, url }) => {
      await emailProvider.send({
        to: user.email,
        subject: "Reset your Bridge password",
        text: `Reset your password: ${url}\n\nIf you didn't request this, you can ignore this email.`,
      });
    },
  },

  emailVerification: {
    sendVerificationEmail: async ({ user, url }) => {
      await emailProvider.send({
        to: user.email,
        subject: "Verify your email for Bridge",
        text: `Verify your email to finish creating your account: ${url}`,
      });
    },
    sendOnSignUp: true,
  },

  session: {
    expiresIn: SESSION_MAX_AGE_SECONDS,
    // Rotates the session's expiry (sliding-window renewal) on active use
    // — the session-fixation mitigation referenced above lives here, not
    // in `advanced` below.
    updateAge: SESSION_UPDATE_AGE_SECONDS,
    // Cached session lookups reduce a DB round trip on every authenticated
    // request; the Identity Service's own profile-summary cache (see
    // docs/core-services.md §1) is a separate, longer-lived cache on top
    // of this.
    cookieCache: {
      enabled: true,
      maxAge: SESSION_COOKIE_CACHE_MAX_AGE_SECONDS,
    },
  },

  advanced: {
    // Cookies are only sent over HTTPS in production. Not a session-
    // rotation control — see `session.updateAge` above for that.
    useSecureCookies: env.NODE_ENV === "production",
  },
});

logger.info("Better Auth initialized");

/**
 * Derived directly from `auth.api.getSession`'s own return type rather
 * than from `auth.$Infer.Session.session`/`.user` (the original approach,
 * which assumed a `{ session, user }` nesting under `$Infer.Session` that
 * didn't hold for the installed better-auth version — `AuthUser` resolved
 * to an unusable type as a result, breaking every consumer, including a
 * missing-import compile error in auth.middleware.ts that only surfaced
 * because the type itself was already broken upstream).
 *
 * This derivation can't drift from reality the same way: `auth.middleware.ts`
 * calls `auth.api.getSession(...)` and destructures `.session`/`.user` off
 * the result — these two types are pulled from that exact same call
 * signature, so they're structurally guaranteed to match what that function
 * actually returns, regardless of how `$Infer` is shaped internally.
 */
type GetSessionResult = Awaited<ReturnType<typeof auth.api.getSession>>;

export type AuthSession = NonNullable<GetSessionResult>["session"];
export type AuthUser = NonNullable<GetSessionResult>["user"];
